// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TravelAgency.Data;

namespace TravelAgency.Migrations
{
    [DbContext(typeof(TravelContext))]
    [Migration("20180612103412_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelAgency.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.Property<string>("Occupation");

                    b.Property<double>("TravelLength");

                    b.Property<bool>("TravelsWithAnimal");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TravelAgency.Models.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AnimalsAllowed");

                    b.Property<int?>("CustomerId");

                    b.Property<double>("Distance");

                    b.Property<string>("EndPosition");

                    b.Property<string>("StartPosition");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("TravelAgency.Models.Journey", b =>
                {
                    b.HasOne("TravelAgency.Models.Customer")
                        .WithMany("Journeys")
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
